//! The declared minimum-consumption floor and its enforcement.
//!
//! A profile declares the minimum number of confirmed shared-layer units a
//! scaffold must start with. There is **no warn-and-continue default**: a
//! warn-only path would restore exactly the silent zero this change removes.
//!
//! Three states, never conflated in the manifest or the console output:
//!
//! - **Met** — generation proceeds.
//! - **Unmet** — a typed `kit-floor-not-met` refusal *before anything is
//!   staged or written*, naming the profile, the declared minimum, the
//!   confirmed set it would have rendered and the provisional set it would
//!   have rendered commented.
//! - **Declared zero** — no registered kit for the ecosystem. Renders
//!   normally, records `minimum_packages: 0` with a `zero_reason`, prints the
//!   reason, and is *never* reported as having met its floor.
//!
//! The only way past an unmet floor is an explicit, non-empty
//! `--kit-exception <reason>`, recorded visibly and dated. An exception
//! nobody wrote down is the same as no exception.

use crate::core::ForgeError;
use crate::kit::registry::KitDescriptor;

/// The declared floor for the .NET profile: every confirmed package with no
/// infrastructure requirement. A single declared field, so the owner can
/// change it without touching the mechanism.
pub const DEFAULT_MINIMUM_PACKAGES: usize = 6;

/// A recorded, dated floor exception.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq, Eq)]
pub struct FloorException {
    /// The operator's non-empty reason. Never inferred, defaulted or
    /// generated by Forge.
    pub reason: String,
    /// The floor this exception bypassed.
    pub floor: usize,
    /// The confirmed set actually declared — the shortfall, stated.
    pub declared: usize,
    pub recorded_at: String,
}

/// Why a floor exception could not be recorded.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KitExceptionRequired {
    /// `--kit-exception` was passed with an empty or whitespace-only reason.
    EmptyReason,
}

impl KitExceptionRequired {
    fn describe(self) -> &'static str {
        match self {
            Self::EmptyReason => "an empty or whitespace-only reason is not an exception",
        }
    }
}

/// The outcome of evaluating a profile's kit against its floor.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FloorDecision {
    /// The confirmed set meets or exceeds the declared minimum.
    Met { declared: usize, floor: usize },
    /// The profile declares a recorded zero: no registered kit for its
    /// ecosystem. Distinct from a floor failure and never reported as met.
    DeclaredZero { reason: String },
    /// The floor was unmet and an explicit, reasoned exception was recorded.
    Exception {
        declared: usize,
        floor: usize,
        exception: FloorException,
    },
}

impl FloorDecision {
    /// The `WARN` line to print, if any. A declared zero and a recorded
    /// exception both warn; a met floor does not.
    pub fn warning(&self, profile: &str) -> Option<String> {
        match self {
            Self::Met { .. } => None,
            Self::DeclaredZero { reason } => Some(format!(
                "WARN: profile '{profile}' declares a shared-layer consumption zero: {reason}"
            )),
            Self::Exception { floor, .. } => Some(format!(
                "WARN: profile '{profile}' bypassed its shared-layer consumption floor of {floor} \
                 with a recorded exception"
            )),
        }
    }

    /// True only when the floor was actually met. A declared zero is never
    /// "met".
    pub fn floor_met(&self) -> bool {
        matches!(self, Self::Met { .. })
    }
}

/// How many confirmed units a descriptor offers. A confirmed package counts
/// one; the vendored token asset set counts as one confirmed unit, so the JS
/// profiles get a floor of 1 without inventing a package for them.
pub fn confirmed_count(descriptor: &KitDescriptor) -> usize {
    let packages = descriptor.confirmed().len();
    let assets = usize::from(!descriptor.assets.is_empty());
    packages + assets
}

/// Evaluate a profile's kit against its floor.
///
/// `exception` is the operator's `--kit-exception <reason>`, if any. Every
/// refusal happens here, before staging, so a failed `forge new` never leaves a
/// half-wired directory or a registered project row.
pub fn check_floor(
    profile: &str,
    descriptor: &KitDescriptor,
    exception: Option<&str>,
    generated_at: &str,
) -> Result<FloorDecision, ForgeError> {
    if descriptor.reference.is_declared_zero() {
        let reason = descriptor
            .reference
            .zero_reason
            .clone()
            .unwrap_or_else(|| "no zero_reason recorded".to_string());
        return Ok(FloorDecision::DeclaredZero { reason });
    }

    // An exception is only meaningful for a floor that actually failed. An
    // operator may not record one for a floor that was met, so a met floor
    // reports that no exception was recorded.
    let declared = confirmed_count(descriptor);
    let floor = descriptor.reference.minimum_packages;
    if declared >= floor {
        return Ok(FloorDecision::Met { declared, floor });
    }

    let Some(raw) = exception else {
        return Err(ForgeError::KitFloorNotMet {
            reason: floor_not_met_reason(profile, descriptor, declared, floor),
        });
    };
    let reason = raw.trim();
    if reason.is_empty() {
        return Err(ForgeError::KitExceptionReasonRequired {
            reason: format!(
                "--kit-exception on profile '{profile}' was given {}; \
                 re-run with a non-empty reason or drop the flag; \
                 nothing was staged and no project was registered",
                KitExceptionRequired::EmptyReason.describe()
            ),
        });
    }
    Ok(FloorDecision::Exception {
        declared,
        floor,
        exception: FloorException {
            reason: reason.to_string(),
            floor,
            declared,
            recorded_at: generated_at.to_string(),
        },
    })
}

fn floor_not_met_reason(
    profile: &str,
    descriptor: &KitDescriptor,
    declared: usize,
    floor: usize,
) -> String {
    let confirmed = descriptor.confirmed_names().join(", ");
    let provisional = descriptor.provisional_names().join(", ");
    format!(
        "profile '{profile}' declares a minimum shared-layer consumption of {floor} for kit '{}' \
         but only {declared} confirmed unit(s) are available; nothing was staged and no project \
         was registered. confirmed (would have been restored): {}; provisional (would have been \
         rendered commented, and does not count toward the floor): {}",
        descriptor.reference.id,
        if confirmed.is_empty() {
            "none".to_string()
        } else {
            confirmed
        },
        if provisional.is_empty() {
            "none".to_string()
        } else {
            provisional
        }
    )
}
