/** Generated from tokens.json. Do not edit. */
export const tokens = { color: { background: "var(--color-background)", surface: "var(--color-surface)", foreground: "var(--color-foreground)", muted: "var(--color-muted)", mutedForeground: "var(--color-muted-foreground)", primary: "var(--color-primary)", primaryHover: "var(--color-primary-hover)", onPrimary: "var(--color-on-primary)", border: "var(--color-border)", danger: "var(--color-danger)", success: "var(--color-success)", warning: "var(--color-warning)", focusRing: "var(--focus-ring)" }, space: { 1: "var(--space-1)", 2: "var(--space-2)", 3: "var(--space-3)", 4: "var(--space-4)", 6: "var(--space-6)", 8: "var(--space-8)" }, radius: { sm: "var(--radius-sm)", md: "var(--radius-md)", lg: "var(--radius-lg)", full: "var(--radius-full)" }, font: { sans: "var(--font-sans)", body: "var(--font-body)", small: "var(--font-small)", large: "var(--font-large)", title: "var(--font-title)" }, component: { "button.minHeight": "var(--component-button-min-height)", "button.radius": "var(--component-button-radius)", "control.minHeight": "var(--component-control-min-height)", "control.radius": "var(--component-control-radius)" } } as const;

/** Every declared token name and its alias-resolved value. */
export const tokenValues = { "--color-slate-50": "#f8fafc", "--color-slate-100": "#f1f5f9", "--color-slate-300": "#cbd5e1", "--color-slate-500": "#64748b", "--color-slate-700": "#334155", "--color-slate-900": "#0f172a", "--color-blue-200": "#bfdbfe", "--color-blue-300": "#93c5fd", "--color-blue-600": "#1d4ed8", "--color-blue-700": "#1e40af", "--color-red-300": "#fca5a5", "--color-red-700": "#b91c1c", "--color-green-300": "#86efac", "--color-green-700": "#15803d", "--color-amber-300": "#fcd34d", "--color-amber-700": "#b45309", "--color-white": "#ffffff", "--color-focus-ring": "#1d4ed8", "--space-1": "0.25rem", "--space-2": "0.5rem", "--space-3": "0.75rem", "--space-4": "1rem", "--space-6": "1.5rem", "--space-8": "2rem", "--radius-sm": "0.25rem", "--radius-md": "0.5rem", "--radius-lg": "0.75rem", "--radius-full": "9999px", "--font-sans": "Outfit, system-ui, sans-serif", "--font-body": "1rem", "--font-small": "0.875rem", "--font-large": "1.125rem", "--font-title": "1.5rem", "--color-background": "#f8fafc", "--color-surface": "#ffffff", "--color-foreground": "#0f172a", "--color-muted": "#f1f5f9", "--color-muted-foreground": "#334155", "--color-primary": "#1d4ed8", "--color-primary-hover": "#1e40af", "--color-on-primary": "#ffffff", "--color-border": "#64748b", "--color-danger": "#b91c1c", "--color-success": "#15803d", "--color-warning": "#b45309", "--focus-ring": "#1d4ed8", "--component-button-min-height": "2.5rem", "--component-button-radius": "0.5rem", "--component-control-min-height": "2.5rem", "--component-control-radius": "0.5rem" } as const;

/** Semantic color values resolved from tokens.json for framework theme adapters. */
export const semanticColorValues = { light: { background: "#f8fafc", surface: "#ffffff", foreground: "#0f172a", muted: "#f1f5f9", mutedForeground: "#334155", primary: "#1d4ed8", primaryHover: "#1e40af", onPrimary: "#ffffff", border: "#64748b", danger: "#b91c1c", success: "#15803d", warning: "#b45309", focusRing: "#1d4ed8" }, dark: { background: "#0f172a", surface: "#334155", foreground: "#f8fafc", muted: "#334155", mutedForeground: "#f1f5f9", primary: "#93c5fd", primaryHover: "#bfdbfe", onPrimary: "#0f172a", border: "#cbd5e1", danger: "#fca5a5", success: "#86efac", warning: "#fcd34d", focusRing: "#bfdbfe" } } as const;

export type TokenName = keyof typeof tokenValues;
export type PlatformTheme = 'light' | 'dark';
export type SemanticColorName = keyof typeof semanticColorValues.light;
